### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by chasgames** [rook2pawn/curl-paste#2]
Hi there

Is there an install guide for this repo? I would like to try it out

Thanks!

**Comment by rook2pawn** [comment]
Sure! @chasgames 

https://github.com/rook2pawn/curl-paste#getting-started

**Comment by chasgames** [comment]
Thanks rook2pawn,

I finally got round to making a docker image for it :) 

https://github.com/chasgames/docker-curlpaste
